# -*- coding: utf-8 -*-
"""lab_cycle_3_q2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lt5eaNywGjQQFMKGRGgUKMP-aFb7SY1V
"""

from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

def compute_PCA():
  n, m = map(int, input("Enter rows and column with a space : ").split()) 
  A = array([input("Enter elements row by row separated by a space : ").strip().split() for _ in range(n)], int)
  print(A)
  M = mean(A, axis=0)
  C = A - M
  V = cov(C.T)
  values, vectors = eig(V)
  projection_matrix = (vectors.T[:][:2]).T
  P = projection_matrix.T.dot(C.T)
  print(P.T)

compute_PCA()