# -*- coding: utf-8 -*-
"""Question 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izgqxquAne1gzaGD-vLZ23wJ6SBYYxTn
"""

#2.Develop a program to read the three sides of two triangles and calculate the area of both. Define a function to read the three sides
#  and call it. Also, define a function to calculate the area. Print the total area enclosed by both triangles and each triangle's contribution (%) 
#  towards it.

def getsides():              # To get the sides of the triangles from the user
  a=int(input("Enter the first side length : "))
  b=int(input("Enter the second side length : "))
  c=int(input("Enter the third side length : "))
  return a,b,c
def area(a,b,c):             # To calculate the area of the triangle
  s=(a+b+c)//2
  p=s*(s-a)*(s-b)*(s-c)
  ar=p**0.5
  return(ar)

print("Triangle 1")
a,b,c=getsides()
print("Triangle 2")
p,q,r=getsides()
A1=area(a,b,c)
A2=area(p,q,r)
print("Area of triangle 1 is : ",A1)
print("Area of triangle 2 is : ",A2)
Total_area=A1+A2
print("Total area : ",Total_area)
percont1=(A1/Total_area)*100
percont2=100-percont1
print("The percentage contribution of triangle 1 to the total area is : ",percont1)
print("The percentage contribution of triangle 2 to the total area is : ",percont2)

"""<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky">Test cases no.</th>
    <th class="tg-0pky">                                                               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    Description                                                      </th>
    <th class="tg-0pky">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Input&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="tg-0pky">Expected Outcome</th>
    <th class="tg-0pky">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Actual Outcome</th>
    <th class="tg-0pky">&nbsp;&nbsp;&nbsp;Result&nbsp;&nbsp;&nbsp;&nbsp;</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1</td>
    <td class="tg-0pky">&nbsp;&nbsp;Area of triangle 1</td>
    <td class="tg-0pky">&nbsp;&nbsp;&nbsp;3,4,5</td>
    <td class="tg-0pky">            6</td>
    <td class="tg-0pky">         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6.0</td>
    <td class="tg-0pky">&nbsp;&nbsp;&nbsp;&nbsp;True</td>
  </tr>
  <tr>
    <td class="tg-0pky">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2</td>
    <td class="tg-0pky">&nbsp;&nbsp;Area of triangle 2</td>
    <td class="tg-0pky">&nbsp;&nbsp;5,12,13</td>
    <td class="tg-0pky">           30</td>
    <td class="tg-0pky">        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 30.0</td>
    <td class="tg-0pky">&nbsp;&nbsp;&nbsp;&nbsp;True</td>
  </tr>
</tbody>
</table>
"""