# -*- coding: utf-8 -*-
"""Lab_cycle_2_Q_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12gplNHSt7HdqRObOgWmKhP63IKkOIDwv
"""

'''3.
1.Read the file 'iris.json' as a text file :

2 Create a list having each line of the file as an element
3 Convert it into a list of dictionary objects.
4 Show the details of all flowers whose species is "setosa".
5 Print the minimum petal area and max sepal area in each species
6 Sort the list of dictionaries according to the total area are sepal and petal.'''

import json
import math
with open('/content/iris.json') as f:
    lines=f.read()
    #list1 initialized to store each line
    list1=[]
    for i in lines.split(" "):
            list1=list1+[i]
    print(list1,"\n")
    print()
    #To print dictionary objects
    print("Dictionary objects are : ")
    for i in list1:
        print(i,end=' ')  
    print()

    print("Details of all flowers whose species is 'Setosa'",)
    for i in list1:
        if (i["species"]=='setosa'):
            print(i)
    species_list=[]
    for i in list1:
        species_list.append(i["species"])
    print("The list of the species is : ",species_list)   

    unique_species_list=[]
    duplicate_species_list=[]
    for i in species_list:
        if i in unique_species_list:
            duplicate_species_list=duplicate_species_list+i
    print("List of unique species ",unique_species_list,end="\n")
    areaof_sepal=[]
    areaof_petal=[]
    list2=[]
    list1=list2
    for i in list2:
         sepal_area = (i["sepalLength"]*i["sepalWidth"])
         petal_area = (i["petalLength"]*i["petalWidth"])
         total_area = (sepal_area+petal_area)
         i.update({"sepalarea":sepal_area})
         i.update({"petalarea":petal_area})
         i.update({'totalarea':total_area})
    for i in species_list:
        print(i.capitalize())
        for j in list1:
            if(j['species']==i):
                areaof_sepal.append(j['sepalLength']*j['sepalWidth'])
                areaof_petal.append(j['petalLength']*j['petalWidth'])
    print("Maximum sepal area in ",i.capitalize(),"is :",max(areaof_sepal))
    print("Maximum peta area in ",i.capitalize(),"is :",max(areaof_petal))
    print()
    sorted_l = (sorted(list2, key = lambda i:i['total_area'] ))
    for i in sorted_l:
        print(i)

import json

myJson =  open('iris.json', 'r')
jsonData = myJson.read()
jsonList = json.loads(jsonData)

#list having each line of json as elements
print("List having each line of json as elements")
print(jsonList)
print("\n")

#list having dictionary of objects.
print("List of Dictionary Objects")
for i in jsonList:
  #printing each dictionary
  print(i)
print("\n")

#printing the details of only setosa.
print("Details of Flowers whose species is Setosa")
for i in jsonList:
  if(i['species']=='setosa'):
    print(i)

#list to store species names.
listOfSpeciesName = list()
for i in jsonList:
  #appeding the different species name to the list.
  listOfSpeciesName.append(i['species'])  

#converting the list to set inorder to remove duplicates, so only unique items are there.
listOfSpeciesName = set(listOfSpeciesName)
#print(listOfSpeciesName)

print('\n')
#initialising two list to store sepal and petal area.
sepal_area = list()
petal_area = list()
for i in listOfSpeciesName:
  #printing the name of the species.
  print(i.capitalize())
  for j in jsonList:
    #calculates the petal and sepal area of each species.
    if(j['species']==i):
      sepal_area.append(j['sepalLength']*j['sepalWidth'])
      petal_area.append(j['petalLength']*j['petalWidth'])
  #prints the maximum sepal area and minimum petal area of each species.
  print("Maximum Sepal Area in ",i.capitalize()," is ",round(max(sepal_area),2))
  print("Minimum Petal Area in ",i.capitalize()," is ",round(min(petal_area),2))  
  print('\n')
  #list is cleared in order to save the area of one particular species at a time. 
  sepal_area.clear()
  petal_area.clear()
print('\n')

#copying the jsonList to another list.
jsonListCopy = list()
jsonListCopy = jsonList
for i in jsonListCopy:
  #calculating the petal area and sepal area.
  petalArea = (i["petalLength"]*i["petalWidth"])
  sepalArea = (i["sepalLength"]*i["sepalWidth"])
  totalArea = (petalArea+sepalArea)
  #adding the key and value (sepal area and petal area ) to the copied list of dictionaries.
  # i.update({"sepalArea":sepalArea})
  # i.update({"petalArea":petalArea})
  i.update({'totalArea':totalArea})

#sorting the list according of petal area and sepal area.
sortedList = (sorted(jsonListCopy, key = lambda i:i['totalArea'] ))
#sortedList = (sorted(jsonListCopy, key = lambda i: (i['sepalArea'])))

print("The Sorted List")
#printing the sorted list.
for i in sortedList:
  # i.pop('sepalArea')
  # i.pop('petalArea')
  # i.pop('totalArea)
  print(i)

myJson.close()