# -*- coding: utf-8 -*-
"""Question 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbQzarHLCPwSeSIbwgCfVuzErmAxtYv-
"""

#3. Develop a program to read the employee's name, code, and basic pay and calculate the gross salary, deduction,
# and net salary according to the following conditions. Define a function to find each of the components. Finally, generate a payslip.

def grosssal():   # to calculate gross salary
  gs=BP+DA+HRA+MA
  return (gs)
def dedn():       # to calculate deduction
  d=PT+PF+IT 
  return(d)
def netsal(gs,d):  # to calculate net salary
  netsal=gs-d
  return(netsal)


empname=input("Enter the name of the employee : ")
empcode=int(input("Enter the code of the employee : "))
BP=int(input("Enter basic pay : "))
if (BP<10,000):
  DA=0.05*BP
  HRA=0.025*BP
  MA=500
  PT=20
  PF=0.08*BP
  IT=0
elif (BP<30,000 and BP>=10,000):
  DA=0.75*BP
  HRA=0.05*BP
  MA=2500
  PT=60
  PF=0.08*BP
  IT=0
elif (BP<50,000 and BP>=30,000 ):
  DA=0.11*BP
  HRA=0.075*BP
  MA=5000
  PT=60
  PF=0.11*BP
  IT=0.11*BP
else:
  DA=0.25*BP
  HRA=0.11*BP
  MA=7000
  PT=80
  PF=0.12*BP
  IT=0.2*BP
GS=grosssal()
D=dedn()
NetSalary=netsal(GS,D)
print("*******************************************PAYSLIP***********************************************************")
print("Gross salary = ",GS)
print("Deduction = ",D)
print("Net Salary = ",NetSalary)

"""<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky">Test cases no.</th>
    <th class="tg-c3ow">                                                               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    Description                                                      </th>
    <th class="tg-0pky">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Input&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="tg-c3ow">Expected Outcome</th>
    <th class="tg-c3ow">Actual Outcome</th>
    <th class="tg-0pky">&nbsp;&nbsp;&nbsp;Result&nbsp;&nbsp;&nbsp;&nbsp;</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1</td>
    <td class="tg-0pky"> Gross Salary</td>
    <td class="tg-0pky">&nbsp;&nbsp;12000</td>
    <td class="tg-0pky">           13400</td>
    <td class="tg-c3ow">13400</td>
    <td class="tg-c3ow">     True</td>
  </tr>
  <tr>
    <td class="tg-0pky">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2</td>
    <td class="tg-0pky"> Deduction</td>
    <td class="tg-0pky">&nbsp;&nbsp;&nbsp;12000</td>
    <td class="tg-0pky">             980</td>
    <td class="tg-c3ow">          980</td>
    <td class="tg-c3ow">     True</td>
  </tr>
  <tr>
    <td class="tg-0pky">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3</td>
    <td class="tg-0pky"> Net Salary</td>
    <td class="tg-0pky">&nbsp;&nbsp;12000</td>
    <td class="tg-c3ow">12420</td>
    <td class="tg-0pky">        12420</td>
    <td class="tg-c3ow">     True</td>
  </tr>
</tbody>
</table>
"""